# THIS IS AN UNWANTED FILE

# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

use_frameworks!

target 'NoughtsAndCrosses' do
  # Pods for NoughtsAndCrosses
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end
