source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'NoughtsAndCrosses' do
    use_frameworks!
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end