#source ‘https://github.com/CocoaPods/Specs.git’
#global platform for your projectplatform :ios, ‘8.0’# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'NoughtsAndCrosses' dopod 'Alamofire', '~> 3.4'

end# Pods for NoughtsAndCrossestarget 'NoughtsAndCrossesTests' do    inherit! :search_paths    # Pods for testingendtarget 'NoughtsAndCrossesUITests' do    inherit! :search_paths    # Pods for testingend