# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'


source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
#use_frameworks!
#
#target 'NoughtsAndCrosses' do
#
#end

target 'NoughtsAndCrosses' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
      pod 'Alamofire', '~> 3.4'
      pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'


  # Pods for NoughtsAndCrosses

  target 'NoughtsAndCrossesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoughtsAndCrossesUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  

end
